### ISSUE TITLE
Perf-Test: Token transfer has already been recorded

### ISSUE THREAD

**Issue by eberger727** [hyperledger/firefly#383]
During a performance test of broadcasts, private messages, and tokens, each at 10 tx/sec, the following two errors were encountered ~2 hours into the test:
- `Token transfer '47629.0.39' has already been recorded - ignoring` (Logged [here](https://github.com/hyperledger/firefly/blob/main/internal/events/tokens_transferred.go#L79) in FF)
- `WS ws://tokens_0:3000/api/ws send failed: write tcp 192.168.160.14:48548-\u003e192.168.160.12:3000: write: broken pipe` (Logged [here](https://github.com/hyperledger/firefly/blob/main/pkg/wsclient/wsclient.go#L238) in wsclient package)

<img width="1669" alt="tokensError" src="https://user-images.githubusercontent.com/17093033/148329968-bbf14d4d-1a0e-4afe-9423-53bfd36f8491.png">

[tokensError.log.zip](https://github.com/hyperledger/firefly/files/7819529/tokensError.log.zip)

**Comment by awrichar** [comment]
Seems like a transient issue that recovered (ie a websocket event was received twice before it could be successfully acked, and the duplicate was ignored). I can double-check the detailed logs to confirm though.

**Comment by awrichar** [comment]
Ah so this one is benign: `Token transfer '47629.0.39' has already been recorded - ignoring`.
But this one, not so much: `WS ws://tokens_0:3000/api/ws send failed`

Looks like the websocket failed to send an `ack` for a token event and never retried. Consequently the connector just stopped delivering token events.

**Comment by awrichar** [comment]
From the `wsclient` [code](https://github.com/hyperledger/firefly/blob/1c37bfcaee1a54dd2e1ca065271f694dceb6639b/pkg/wsclient/wsclient.go#L238), I'd expect `WS %s send failed` to be followed by a return from the `sendLoop`, which would trigger closing of the `sendDone` channel, which would trigger the case that causes the `receiverLoop` to log `WS %s closing reader after send error`. I do not see this log.

**Comment by awrichar** [comment]
Should be fixed by #387

**Comment by eberger727** [comment]
Running the test again, I'm still seeing `ERROR WS ws://tokens_0:3000/api/ws send failed: write tcp 192.168.144.14:57142-'192.168.144.13:3000: write: broken pipe pid=1\n","stream":"stderr","time":"2022-01-07T03:21:35.279279475Z"}`

It appears that mints are still being confirmed, test workers are still able to proceed, but at a much slower rate:
<img width="1466" alt="Screen Shot 2022-01-06 at 10 24 52 PM" src="https://user-images.githubusercontent.com/17093033/148486562-ca7b3ce8-8b2e-4340-9183-ced46b1fa587.png">

[mint.log.zip](https://github.com/hyperledger/firefly/files/7826129/mint.log.zip)

**Comment by awrichar** [comment]
Looks possibly better since the reader gets closed in this case (albeit much later than I'd expect)... I'll reopen to examine the new symptom.

**Comment by awrichar** [comment]
After a closer look, it seems like the websocket connects successfully after each disconnect - so nothing immediately jumps out at me there. I do see a lot of transfer events per transaction - which possibly indicates a large quantity of NFTs being minted at once (and that's a very unoptimized path). Could you confirm if you were testing non-fungible tokens, and if so, maybe we should limit to 100 or so being minted at a time. Want to get a sane baseline before we stress it too much.
